name: Telegram Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Free disk space
      run: |
        # 清理Docker镜像
        docker image prune -a -f
        # 清理不需要的预装软件
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        # 清理apt缓存
        sudo apt-get clean
        # 清理swap
        sudo swapoff -a
        sudo rm -f /mnt/swapfile
        # 显示剩余磁盘空间
        df -h
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Install required SDK components
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platforms;android-35" "build-tools;35.0.0" "ndk;27.2.12479018"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew :TMessagesProj_App:assembleAfatDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: Telegram-Debug-APK
        path: TMessagesProj_App/build/outputs/apk/afat/debug/*.apk
        
